from __future__ import annotations

from pathlib import Path
from typing import Any

VALID_TARGETS = {"codex", "claude_code", "hermes", "generic_agent_skill"}


def prepare_runtime_install_bundle(skill_path: str, runtime_target: str) -> dict[str, Any]:
    target = runtime_target if runtime_target in VALID_TARGETS else "generic_agent_skill"
    path = Path(skill_path)
    warnings: list[str] = []
    if not path.exists() or not path.is_dir():
        return {
            "target": target,
            "instructions_path": "",
            "warnings": [f"Skill 目录不存在: {skill_path}"],
        }
    if runtime_target not in VALID_TARGETS:
        warnings.append(f"未知 runtime_target={runtime_target}，已按 generic_agent_skill 生成说明。")

    if target == "codex":
        destination = "Codex 的本地 skills 目录。常见为用户配置的 ~/.codex/skills/，但请以当前 Codex 官方文档和本机配置为准。"
        invoke = "安装后，在 Codex 中通过该 skill 的名称触发。"
    elif target == "claude_code":
        destination = "Claude Code 的 skills 目录。常见为项目或用户级 .claude/skills/，但请以 Claude Code 官方文档为准。"
        invoke = "安装后，在 Claude Code 中按该 Skill 的触发说明或 slash command 使用。"
    elif target == "hermes":
        destination = "Hermes 的 skills 目录。无法从本项目可靠判断具体路径，请根据 Hermes 官方文档选择。"
        invoke = "安装后，在 Hermes 中按 Skill 名称或命令入口使用。"
    else:
        destination = "任意兼容 Agent Skills 的 runtime skills 目录。具体路径请查看对应 runtime 官方文档。"
        invoke = "安装后，根据 runtime 的 skill 发现机制触发。"

    text = f"""# Runtime Install Instructions

Target runtime: `{target}`

## What this is

This package was generated by AI Clone Persona Skill Foundry. It is a compatible Agent Skill package, not an automatically installed runtime plugin.

## Destination

Copy this entire directory:

```text
{path}
```

to:

```text
{destination}
```

## Invocation

{invoke}

## Validation Boundary

- Structure validation can be completed inside AI Clone.
- Dry-run simulation can be completed inside AI Clone with the configured LLM provider.
- Actual runtime execution is only confirmed after you install this package in Codex / Claude Code / Hermes / another compatible runtime and run a real task there.

## Privacy

Do not copy `.env`, databases, upload folders, secret credentials, or unrelated project files. This generated package should only contain generated Skill files and source metadata.
"""
    target_path = path / "install_instructions.md"
    target_path.write_text(text, encoding="utf-8")
    return {"target": target, "instructions_path": str(target_path), "warnings": warnings}
